image: archlinux
packages:
  - curl
  - dash
  - jq
  - mpv
sources:
  - https://git.sr.ht/~krathalan/wtwitch#dev
tasks:
  - test: |
      export LANG="en_US.UTF-8"
      cd wtwitch
      dash test.sh
