image: archlinux
packages:
  - curl
  - dash
  - jq
  - scdoc
  - shellcheck
tasks:
  - scdoc-test: |
      cd wtwitch
      scdoc < wtwitch.1.scd > wtwitch.1
  - shellcheck-test: |
      cd wtwitch
      shellcheck wtwitch
  - unit-tests: |
      cd wtwitch
      mkdir -p ~/.cache ~/.config
      cp -r dummy-data/cache ~/.cache/wtwitch
      cp -r dummy-data/config ~/.config/wtwitch
      dash unit-test-wtwitch.sh
