image: archlinux
packages:
  - curl
  - dash
  - jq
  - scdoc
  - shellcheck-bin
tasks:
  - scdoc-test: |
      cd wtwitch/src
      scdoc < wtwitch.1.scd > wtwitch.1
  - shellcheck-test: |
      cd wtwitch/src
      shellcheck wtwitch
  - unit-tests: |
      export LANG="en_US.UTF-8"
      export TZ="America/Los_Angeles"
      mkdir -p ~/.cache ~/.config
      cd wtwitch/tests
      cp -r dummy-data/cache ~/.cache/wtwitch
      cp -r dummy-data/config ~/.config/wtwitch
      cd ../src
      dash ../tests/unit-test-wtwitch.sh
