image: archlinux
packages:
  - curl
  - dash
  - jq
  - mpv
  - scdoc
  - shellcheck
tasks:
  - scdoc-test: |
      cd wtwitch
      scdoc < wtwitch.1.scd > wtwitch.1
  - shellcheck-test: |
      cd wtwitch
      shellcheck wtwitch
  - script-test: |
      export LANG="en_US.UTF-8"
      cd wtwitch
      dash test.sh
